name: nmap25
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nodejs=18
  - ipywidgets==8.*   # https://github.com/jupyter-widgets/ipywidgets
  # user
  - numpy==1.25.2
  - scipy==1.9.3
  - matplotlib==3.6.2
  - seaborn==0.12.1
  - rise==5.7.1
  - future==0.18.2
  - mpmath==1.3.0
  - pip
  - pip:
    - tqdm==4.66.1
    - PyNAFF==1.1.5
    - Cython==3.0.5
      #- PyHEADTAIL==1.16.1
    - cpymad ==1.14.2
    - pysixtrack ==0.0.6
#    - botorch==0.8.1
#    - cheetah-accelerator==0.5.18
#    - --extra-index-url https://download.pytorch.org/whl/cpu
#    - torch==1.13.1
#    - gym==0.26.2
    - scikit-image==0.19.3
    - pillow==9.2.0
    - longitudinal-tomography==3.4.3
    - ipykernel==6.29.5
#    - tensorflow-cpu==2.11.0
#    - prettytable==3.6.0
#    - stable_baselines3==2.2.1
    - celluloid==0.2.0
